[package]
name = "avalanche-index"
version.workspace = true
edition.workspace = true

[dependencies]
avalanche-model = { path = "../avalanche-model" }
avalanche-nix = { path = "../avalanche-nix" }
avalanche-source = { path = "../avalanche-source" }
serde_json = { workspace = true }
thiserror = { workspace = true }
